//Db list movies
export const moviesData = [
  {
    id: 1, // IDENTIFICADOR DE PELICULA
    name: 'Transformers 1', //NOMBRE DE LA PELICULA
    duracion: 2, // DURACION DE LA PELICULA
    minutos: 23, // MINUTOS DE LA PELICULA
    genero: 'Ciencia ficción', // GENERO DE LA PELICUAL
    anio: 2007, // AÑO DE LA PELICULA
    imageUrl:
      'https://www.themoviedb.org/t/p/original/qe1tFtmKtyiw8OjlCgs7cSqqF8s.jpg', // PORTADA DE LA PELICULA USANDO TMDB
    link: 'https://watchfun.fun/bu/?key=UGLAVkAYXKwCSZu-tyt-GKmoupTfhYu0tv_ghh_wYCespx9J-tyt-RRs6XIc549uuYuFDZ_ghh_NFS9iqj5joR5Cv2cbBYHGWCv_ghh_IYTqo3PW8hKL0osZ3GQTCK9AjSTHxOj3mlBbKKP5ltNM', // URL DEL SERVIDOR DE ALOJAMIENTO EXTERNO
    numgenero: 3, // GENERO AL QUE PERTENECE
    ocultar: true, // SE USA CUANDO LOS ENLACES ESTAN EN MANTENIMIENTO
  },
  {
    id: 2,
    name: 'Transformers 2',
    duracion: 2,
    minutos: 29,
    anio: 2009,
    genero: 'Ciencia ficción',
    imageUrl:
      'https://www.themoviedb.org/t/p/original/hDdTUHlxq6AVOsLG6RVeKP6wGM8.jpg',
    link: 'https://wishembed.pro/e/jxcgt3gzkxnx', // URL de la película Transformers 2
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 3,
    name: 'Transformers 3',
    duracion: 2,
    minutos: 34,
    genero: 'Ciencia ficción',
    anio: 2011,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/fMqXNNgzTaxalU1ve9KevpELiGe.jpg',
    link: 'https://waaw.to/f/3gLEjwtT8c7R',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 4,
    name: 'Transformers 4',
    duracion: 2,
    minutos: 45,
    anio: 2014,
    genero: 'Ciencia ficción',
    imageUrl:
      'https://www.themoviedb.org/t/p/original/gNHcZ41J6vNEkICd95FETGwiWho.jpg',
    link: 'https://azipcdn.com/v/q4w3ejy4rcwm',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 5,
    name: 'Transformers 5',
    duracion: 2,
    minutos: 29,
    genero: 'Ciencia ficción',
    anio: 2017,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/yTSaTtpWsZzYGdIp1RjxWX1lC7C.jpg',
    link: 'https://azipcdn.com/v/q4w3ejy4rcwm',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 6,
    name: 'Blade Runner 2049',
    duracion: 2,
    minutos: 44,
    genero: 'Ciencia ficción',
    anio: 2017,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/aBvDBfqCHs0sCXoun7giyHeClb1.jpg',
    link: 'https://azipcdn.com/v/armzk7yyzgyl',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 7,
    name: 'Rápidos y Furiosos X',
    duracion: 2,
    minutos: 44,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/l31hvzHjfj903hGBgL1v3uGGwU8.jpg',
    numgenero: 1,
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    ocultar: true,
  },
  {
    id: 8,
    name: 'Spider-Man',
    duracion: 2,
    minutos: 1,
    genero: 'Ciencia ficción',
    anio: 2002,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/2ufIbl01RhJ9QkSUxD0UjDakxvk.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 9,
    name: 'El increíble hulk',
    duracion: 1,
    minutos: 53,
    genero: 'Ciencia ficción',
    anio: 2008,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/p4NYZXVtgKf6aiH65QzzkUVJcsd.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 10,
    name: ' Scooby-Doo y Krypto',
    duracion: 1,
    minutos: 19,
    genero: 'Animación',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/oWspFZp0lfYeykiaPIabaGtiA6U.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 11,
    name: 'Midsommar: El terror no espera la noche',
    duracion: 2,
    minutos: 28,
    genero: 'Terror',
    anio: 2019,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/km0ta4N96yjoZPVy5A3gbcE3Ne8.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 12,
    name: 'Spider-Man: A través del Spider-Verso',
    duracion: 2,
    minutos: 20,
    genero: 'Animación',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/37WcNMgNOMxdhT87MFl7tq7FM1.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 13,
    name: 'Annabel: El Conjuro',
    duracion: 1,
    minutos: 39,
    genero: 'Terror',
    imageUrl:
      'https://www.themoviedb.org/t/p/original/y84GATalgc1VA0GzyFNxCmAHkTN.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 14,
    name: 'Terror bajo la Tierra 5: Lineas de sangre',
    duracion: 1,
    minutos: 39,
    genero: 'Terror',
    anio: 2015,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/eJ2kxo6yzwYvqUOGOBjXTaO8oYQ.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 15,
    name: 'Ballerina',
    duracion: 1,
    minutos: 33,
    genero: 'Terror',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/bcwSsl9pw8ogjNsdwKbcVjMW8eZ.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 16,
    name: 'M3GAN',
    duracion: 1,
    minutos: 42,
    genero: 'Terror',
    anio: 2022,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/ogSpQMynabVu91Bi7AuUA8tshfb.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 17,
    name: 'Scream 6',
    duracion: 2,
    minutos: 3,
    genero: 'Terror',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/rOXdbT6U8q6aEBZ0AvVpXpwAXuK.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 18,
    name: 'Megalodón',
    duracion: 1,
    minutos: 53,
    genero: 'Terror',
    anio: 2018,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/pQARFwPxjZ04ylcE5PmWfqQI1Jw.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 19,
    name: 'El exorcista del Papa',
    duracion: 1,
    minutos: 49,
    genero: 'Terror',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/qcknZEeD71byJ3XSalDDZ5iHpNr.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 20,
    name: 'Five Nights at Freddy’s',
    duracion: 1,
    minutos: 43,
    genero: 'Terror',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/gk5t2xWmtcUjvhoUmvdymY3nR8r.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 21,
    name: 'Muzzle',
    duracion: 1,
    minutos: 40,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/rLu0yO1qCZnWevzofNNFfzJ30tM.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 22,
    name: 'URI: Fuerzas Especiales',
    duracion: 2,
    minutos: 18,
    genero: 'Acción',
    anio: 2019,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/nHvYz0gpOUut13ogJZpccok2A6L.jpg',
    link: 'https://play.google.com/880ad3ed-465b-4967-85ec-93355656d49f',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 23,
    name: 'El pacto',
    duracion: 2,
    minutos: 3,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/nq7NbZtNfIHyL1NXPV1EiG4XQ7u.jpg',
    link: 'https://www.youtube.com/watch?v=02PPMPArNEQ',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 24,
    name: 'The Equalizer: El Justiciero',
    duracion: 2,
    minutos: 12,
    genero: 'Acción',
    anio: 2002,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/2jXniycpyW4n4mneYcLNcVpAnX4.jpg',
    link: 'https://youtu.be/VjctHUEmutw?si=LDco3qcFGx-l6rj4',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 25,
    name: 'xXx: Triple X',
    duracion: 2,
    minutos: 4,
    genero: 'Acción',
    anio: 2015,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/ewGhwS8dbAfFDJBEpbsWOuwS4Ov.jpg',
    link: '',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 26,
    name: 'Asediado',
    duracion: 1,
    minutos: 43,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/5ZfU30EpuAutv2zEZhPtRGOkiTU.jpg',
    link: 'https://youtu.be/h1PcWQcsQuE?si=QFps02EiPWbsdb9h',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 27,
    name: 'Black Adam',
    duracion: 2,
    minutos: 5,
    genero: 'Acción',
    anio: 2022,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/mPTzXksC8HcAj6EM6WjZFJVJEzF.jpg',
    link: 'https://youtu.be/a1mcS4tKGNg?si=fKccrZxfFyhNLF9c',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 28,
    name: 'Venom: Carnage Liberado',
    duracion: 1,
    minutos: 37,
    genero: 'Acción',
    anio: 2021,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/6YBaviE6fSchvXBWv07JveUZeZU.jpg',
    link: 'https://youtu.be/kxDcW1pFjYY?si=MpQN9Bcg-CKAsDrG',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 29,
    name: 'Murder City',
    duracion: 1,
    minutos: 25,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/gZ1YbdkwyTCmVxZxh1otFnMEnOs.jpg',
    link: 'https://youtu.be/g1ElFfl_7JU',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 30,
    name: 'Blue Beetle',
    duracion: 2,
    minutos: 8,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/z5mkvXYNRauSzHdZgxAj6MzrLTY.jpg',
    link: 'https://youtu.be/dAkmmZMjKNY',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 31,
    name: 'Flash',
    duracion: 2,
    minutos: 24,
    genero: 'Ciencia ficción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/mN8TsVWd01qjnz9f4DYkw2LPJH6.jpg',
    link: 'https://youtu.be/-wMDfj7k8kM',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 32,
    name: 'Coco',
    duracion: 1,
    minutos: 49,
    genero: 'Animación',
    anio: 2017,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/lUZZhYLLDU4g4XGQ5tvjYNVytxc.jpg',
    link: 'https://youtu.be/bbHNxXqGTNQ',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 33,
    name: 'Bajo la misma estrella',
    duracion: 2,
    minutos: 5,
    genero: 'Romance',
    anio: 2014,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/wWtK2Kg4afUaQ2LVzQKsdcvJnLa.jpg',
    link: 'https://youtu.be/3Ixw15DE-xY',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 34,
    name: 'Hipnosis: Arma Invisible',
    duracion: 1,
    minutos: 34,
    genero: 'Ciencia ficción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/oIgnzY3tGS153ftqAmbyO0vcWjQ.jpg',
    link: 'https://youtu.be/FmWFNHxoDwI',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 35,
    name: '¡Shazam! La furia de los dioses',
    duracion: 2,
    minutos: 10,
    genero: 'Ciencia ficción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/xsp09n1vooagSYoOVBXyzdjc792.jpg',
    link: 'https://youtu.be/ChLbN1M9Zbo',
    numgenero: 3,
    ocultar: true,
  },
  {
    id: 36,
    name: 'Triple X: Reactivado',
    duracion: 1,
    minutos: 47,
    genero: 'Acción',
    anio: 2017,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/teGyysfsoCqQwHHSCQXX9yNo8Xm.jpg',
    link: 'https://youtu.be/-ziu6JzJTZ0',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 37,
    name: 'Maze Runner: Correr o Morir',
    duracion: 1,
    minutos: 43,
    genero: 'Acción',
    anio: 2014,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/egKi4jZKKVZzR8NaaNjEwMpEgHs.jpg',
    link: 'https://imgur.com/a/YfoCizh',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 38,
    name: 'Creed III',
    duracion: 1,
    minutos: 56,
    genero: 'Acción',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/fcFMd3HdyX7r5gtFwVnn2qr5Yhq.jpg',
    link: 'https://imgur.com/a/YfoCizh',
    numgenero: 1,
    ocultar: true,
  },
  {
    id: 39,
    name: 'El conjuro',
    duracion: 1,
    minutos: 52,
    genero: 'Terror',
    anio: 2013,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/10ir0eISr3p1MF1mjZwGTx7u4vv.jpg',
    link: 'https://imgur.com/a/YfoCizh',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 40,
    name: 'SAW X: El juego del miedo',
    duracion: 1,
    minutos: 58,
    genero: 'Terror',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/hx6riiVXOLo3fdFaT3dU9gSlHIb.jpg',
    link: 'https://imgur.com/a/YfoCizh',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 41,
    name: 'Agnes',
    duracion: 1,
    minutos: 33,
    genero: 'Terror',
    anio: 2021,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/d6ZjUt2rigreV0ENiEXTTOFTkUD.jpg',
    link: 'https://gist.github.com/mazapanexa/7602172b75188d632b20f26da084d967',
    numgenero: 4,
    ocultar: true,
  },
  {
    id: 42,
    name: 'After: Para siempre',
    duracion: 1,
    minutos: 33,
    genero: 'Romance',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/jO3VGQi5sHIj2BGS963g1F74yCq.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 43,
    name: 'Culpa mía',
    duracion: 1,
    minutos: 57,
    genero: 'Romance',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/e2XUzlj6SzD4jL8ldfn3lkMsFch.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 44,
    name: 'Yo antes de ti',
    duracion: 1,
    minutos: 50,
    genero: 'Romance',
    anio: 2016,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/k7rVpfmFq1hlRiP5qAcK0jv08rj.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 45,
    name: 'Hazme el favor',
    duracion: 1,
    minutos: 44,
    genero: 'Romance',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/hhK1R98Do6HYZIP0yvBBW2hDnOk.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 46,
    name: 'After: Amor infinito',
    duracion: 1,
    minutos: 34,
    genero: 'Romance',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/xbMYV7fR9ygl5PGlM6MBZ7Vgjef.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id:47,
    name: 'Ghosteado',
    duracion: 1,
    minutos: 57,
    genero: 'Romance',
    imageUrl:
      'https://www.themoviedb.org/t/p/original/zSw2JeQ03GivcS4VKJmWK5sYi1F.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 0,
    ocultar: true,
  },
  {
    id: 48,
    name: 'La cenicienta',
    duracion: 1,
    minutos: 45,
    genero: 'Romance',
    imageUrl:
      'https://www.themoviedb.org/t/p/original/zqWF0q31AgZTPDlCEgQlMNopnHy.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 0,
    ocultar: true,
  },
  {
    id: 49,
    name: 'Forrest Gump',
    duracion: 2,
    minutos: 22,
    genero: 'Romance',
    anio: 1994,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/azV6hV99lYkdhydsQbJCI6FqMl4.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 50,
    name: 'El joven manos de tijera',
    duracion: 1,
    minutos: 45,
    genero: 'Romance',
    anio: 1960,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/6dnhsZMpob10sDAfsFwz0Z94vrw.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 51,
    name: 'Titanic',
    duracion: 3,
    minutos: 15,
    genero: 'Romance',
    anio: 1997,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/rBTJZrf5UWaxzg5YJd2eqpeaSvm.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 52,
    name: 'Ella',
    duracion: 2,
    minutos: 6,
    genero: 'Romance',
    anio: 2013,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/xPby6SuDafflEL7EWVHTFmhJsDp.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 53,
    name: 'A todos los chicos de los que me enamoré',
    duracion: 1,
    minutos: 40,
    genero: 'Romance',
    anio: 2018,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/2sYSsHPVblMSdRjVAPQP6JxMQJB.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 54,
    name: 'Una chica del siglo XX',
    duracion: 1,
    minutos: 59,
    genero: 'Romance',
    anio: 2022,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/4kU4QFgExCgybhcKv1mzZ0vuND6.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 55,
    name: 'PAW Patrol',
    duracion: 1,
    minutos: 32,
    genero: 'Animación',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/uwkqb5ZiS7jhQH5gwtkiTdd54w6.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 56,
    name: 'Elementos',
    duracion: 1,
    minutos: 33,
    genero: 'Animación',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/5BdO9mogSS2VLL2Gl9Zkz78jgMR.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 57,
    name: 'La liga de la justicia: Mundo Bélico',
    duracion: 1,
    minutos: 29,
    genero: 'Animación',
    anio: 2023,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/OKeu0tqBBdcnKVABplvLYhOEZT.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 58,
    name: 'Up',
    duracion: 1,
    minutos: 36,
    genero: 'Animación',
    anio: 2009,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/vSdpOU6rDK7IpmOD7iAvlZdMUCc.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 59,
    name: 'Caroline y la puerta secreta',
    duracion: 1,
    minutos: 49,
    genero: 'Animación',
    anio: 2009,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/bDBmImiBOa29jBBb4Bkc1uc1JYV.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 60,
    name: 'Shrek: Para Siempre el capítulo final',
    duracion: 1,
    minutos: 34,
    genero: 'Animación',
    anio: 2001,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/xWZZVYVXDlRNvxY9XYdQwspV7Rj.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 61,
    name: 'Toy Story',
    duracion: 1,
    minutos: 21,
    genero: 'Animación',
    anio: 1995,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/jvn7wy3RSNEXnFSXLpH2of2LcV6.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 62,
    name: 'Garfield',
    duracion: 1,
    minutos: 49,
    genero: 'Animación',
    anio: 2002,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/pMQKL3Dx40au9e172ARVUWsT4qH.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 63,
    name: 'Grandes Heroes',
    duracion: 1,
    minutos: 42,
    genero: 'Animación',
    anio: 2014,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/sq31A8yZeKWgvMpwIiZDNDUKBxf.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 2,
    ocultar: true,
  },
  {
    id: 64,
    name: 'Theatre: A Love Story',
    duracion: 2,
    minutos: 16,
    genero: 'Romance',
    anio: 2020,
    imageUrl:
      'https://www.themoviedb.org/t/p/original/fbQwLYgzTui77gr0drYG3xA4d8S.jpg',
    link: 'https://drive.google.com/file/d/1FB_IsKchfHpbS_7yyReTwaQCetGSi1y8/view?usp=sharing',
    numgenero: 5,
    ocultar: true,
  },
  {
    id: 63,
    name: 'La Sirenita',
    duracion: 2,
    minutos: 15,
    genero: 'Romance',
    anio:2023,
    imageUrl: 'https://www.themoviedb.org/t/p/original/yGZBQuu2UFMdkYbFKHAWuYOhfqt.jpg',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 5,
    ocultar:true,
  },
  /*
  {
    id: 0,
    name: '',
    duracion: 0,
    minutos: 0,
    genero: '',
    anio: 0000,
    imageUrl: '',
    link: 'https://gist.github.com/7602172b75188d632b20f26da084d967',
    numgenero: 0,
    ocultar:true,
  },
  */
  // Agrega más peliculas
];
